" let g:UltiSnipsExpandTrigger="<c-."
" let g:UltiSnipsListSnippets="<c-/>"
" let g:UltiSnipsJumpForwardTrigger="<c-.>"
" let g:UltiSnipsJumpBackwardTrigger="<c-,>"
" inoremap <expr><c-e> "\<C-R>=UltiSnips#ExpandSnippet()\<CR>"
inoremap <expr><c-e> "\<C-R>=UltiSnips#ExpandSnippetOrJump()\<CR>"
" inoremap <expr><c-;> "\<C-R>=UltiSnips#JumpBackwards()\<CR>"
